create user if not exists scott password 'tiger';
alter user scott admin true;

create schema template;

create table template.person (
  id integer generated by default as identity primary key,
  first_name varchar(30) not null,
  last_name varchar(30) not null
);

insert into template.person(first_name, last_name) values ('James', 'Carter');
insert into template.person(first_name, last_name) values ('Helen', 'Leary');
insert into template.person(first_name, last_name) values ('Linda', 'Douglas');